export enum Color {
  A = 'aqua',
  B = 'blue',
  C = 'chocolate',
  D = 'darkred',
  E = 'chartreuse',
  F = 'firebrick',
  G = 'gold',
  H = 'honeydew',
  I = 'indianred',
  J = 'navajowhite',
  K = 'khaki',
  L = 'lavender',
  M = 'magenta',
  N = 'navajowhite',
  O = 'orange',
  P = 'purple',
  Q = 'antiquewhite',
  R = 'red',
  S = 'salmon',
  T = 'tan',
  U = 'aliceblue',
  V = 'violet',
  W = 'whitesmoke',
  X = 'coral',
  Y = 'yellow',
  Z = 'azure'
}
